name: "Deploy INFLUENCE on Netlify"

on:
  workflow_dispatch:
  push:
    branches:
      - release/staging
      - release/lab
      - master
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Reconfigure git to use HTTPS authentication
        run: |
          git config --global url."https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/".insteadOf "git@github.com:"
      - name: Identify target branch based on current branc
        run: |
          CURRENT_BRANCH=${GITHUB_REF_NAME}
          echo "CURRENT_BRANCH = $CURRENT_BRANCH"
          if [[ $CURRENT_BRANCH == 'master' ]]; then
            DEPLOY_BRANCH='deploy/production'
          elif [[ $CURRENT_BRANCH == 'release/staging' ]]; then
            DEPLOY_BRANCH='deploy/staging'
          elif [[ $CURRENT_BRANCH == 'release/lab' ]]; then
            DEPLOY_BRANCH='deploy/lab'
          fi
          echo "DEPLOY_BRANCH = $DEPLOY_BRANCH"
          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> "$GITHUB_ENV"
          echo "DEPLOY_BRANCH=${DEPLOY_BRANCH}" >> "$GITHUB_ENV"
      - name: Delete and recreate deploy branch
        run: |
          # setup the username and email
          git --version
          git config user.name "GitHub Actions [Bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git ls-remote --exit-code --heads origin "$DEPLOY_BRANCH" >/dev/null; then
            echo "Git branch '$DEPLOY_BRANCH' exists in the remote repository"
            git branch -d -r $DEPLOY_BRANCH
          else
            echo "Git branch '$DEPLOY_BRANCH' does not exist in the remote repository"
          fi
          git checkout -b "$DEPLOY_BRANCH"
          git push origin "$DEPLOY_BRANCH"
      - name: Generate dummy changes
        run: |
          date > generated.txt
          git config push.autoSetupRemote true
          git add .
          git commit -m "generated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.DEPLOY_BRANCH }}
