name: 'Deploy INFLUENCE on Netlify'

on:
  workflow_dispatch:
  push:
    branches:
      - release/staging
      - release/lab
      - master
    # paths:
    #   - 'influence/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3
      - name: Delete and recreate deploy branch
        shell: bash
        run: |
          BRANCH='deploy/production'
          git ls-remote --exit-code --heads origin $BRANCH >/dev/null 2>&1
          EXIT_CODE=$?
          if [[ $EXIT_CODE == '0' ]]; then
            echo "Git branch '$BRANCH' exists in the remote repository"
            git branch -d -r deploy/production
          elif [[ $EXIT_CODE == '2' ]]; then
            echo "Git branch '$BRANCH' does not exist in the remote repository"
          fi
          git checkout -b deploy/production
          git push origin deploy/production
