name: 'Deploy INFLUENCE on Netlify'

on:
  workflow_dispatch:
  push:
    branches:
      - release/staging
      - release/lab
      - master
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Reconfigure git to use HTTPS authentication
        run: |
          git config --global url."https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/".insteadOf "git@github.com:"
      - name: Identify target branch based on current branc
        run: |
          CURRENT_BRANCH=${GITHUB_REF_NAME}
          echo $CURRENT_BRANCH
          if [[ $CURRENT_BRANCH == 'master' ]]; then
            DEPLOY_BRANCH='deploy/production'
          elif [[ $CURRENT_BRANCH == 'release/staging' ]]; then
            DEPLOY_BRANCH='deploy/staging'
          elif [[ $CURRENT_BRANCH == 'release/lab' ]]; then
            DEPLOY_BRANCH='deploy/lab'
          fi
          echo $DEPLOY_BRANCH
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> "$GITHUB_ENV"
          echo "DEPLOY_BRANCH=$DEPLOY_BRANCH" >> "$GITHUB_ENV"
      - name: Generate dummy changes
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config push.autoSetupRemote true
          git add .
          git commit -m "generated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: $DEPLOY_BRANCH
      # - name: Delete and recreate deploy branch
      #   run: |
      #     BRANCH='deploy/production'
      #     git config --global "url.https://${GH_TOKEN}@github.com/.insteadOf" https://github.com/
      #     # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
      #     # git --version
      #     # git config user.name "GitHub Actions [Bot]"
      #     # git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     # ls .git/refs/heads
      #     (git ls-remote --exit-code --heads origin $BRANCH)
      #     # (git ls-remote --exit-code --heads origin $BRANCH >/dev/null 2>&1)
      #     EXIT_CODE=$?
      #     echo $EXIT_CODE
      #     # if [[ $EXIT_CODE == '0' ]]; then
      #     #   echo "Git branch '$BRANCH' exists in the remote repository"
      #     #   git branch -d -r deploy/production
      #     # elif [[ $EXIT_CODE == '2' ]]; then
      #     #   echo "Git branch '$BRANCH' does not exist in the remote repository"
      #     # fi
      #     # git checkout -b deploy/production
      #     # git push origin deploy/production
