name: "Deploy INFLUENCE on Netlify"

on:
  workflow_dispatch:
  push:
    branches:
      - release/staging
      - release/lab
      - master
permissions:
  contents: write

jobs:
  compute-deploy-branch-and-context:
    runs-on: ubuntu-latest
    steps:
      - name: Identify target branch based on current branch
        id: compute_env
        run: |
          CURRENT_BRANCH=${GITHUB_REF_NAME}
          echo "CURRENT_BRANCH = $CURRENT_BRANCH"
          if [[ $CURRENT_BRANCH == 'master' ]]; then
            DEPLOY_BRANCH='deploy/production'
            NETLIFY_CONTEXT='production'
          elif [[ $CURRENT_BRANCH == 'release/staging' ]]; then
            DEPLOY_BRANCH='deploy/staging'
            NETLIFY_CONTEXT='branch-deploy'
          elif [[ $CURRENT_BRANCH == 'release/lab' ]]; then
            DEPLOY_BRANCH='deploy/lab'
            NETLIFY_CONTEXT='branch-deploy'
          fi
          echo "DEPLOY_BRANCH = $DEPLOY_BRANCH"
          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_OUTPUT
          echo "DEPLOY_BRANCH=${DEPLOY_BRANCH}" >> $GITHUB_OUTPUT
          echo "NETLIFY_CONTEXT=${NETLIFY_CONTEXT}" >> $GITHUB_OUTPUT
    outputs:
      CURRENT_BRANCH: ${{ steps.compute_env.outputs.CURRENT_BRANCH }}
      DEPLOY_BRANCH: ${{ steps.compute_env.outputs.DEPLOY_BRANCH }}
      NETLIFY_CONTEXT: ${{ steps.compute_env.outputs.NETLIFY_CONTEXT }}
  push-envs-to-netlify:
    runs-on: ubuntu-latest
    needs: [compute-deploy-branch-and-context]
    steps:
      - name: Set up NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Netlify CLI
        run: |
          npm install netlify-cli -g
      - name: Push env to Netlify
        run: |
          netlify env:set FROM_GITHUB ${{ secrets.FROM_GITHUB }} --context ${{ needs.compute-deploy-branch-and-context.outputs.NETLIFY_CONTEXT }} --secret
          netlify env:set VAR_FROM_GITHUB ${{ vars.VAR_FROM_GITHUB }} --context ${{ needs.compute-deploy-branch-and-context.outputs.NETLIFY_CONTEXT }} --secret
          netlify env:set NETLIFY_CONTEXT ${{ needs.compute-deploy-branch-and-context.outputs.NETLIFY_CONTEXT }} --context ${{ needs.compute-deploy-branch-and-context.outputs.NETLIFY_CONTEXT }} --secret
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - push-envs-to-netlify
      - compute-deploy-branch-and-context
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Reconfigure git to use HTTPS authentication
        run: |
          git config --global url."https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/".insteadOf "git@github.com:"
      - name: Delete and recreate deploy branch
        run: |
          # setup the username and email
          git --version
          git config user.name "GitHub Actions [Bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B "${{ needs.compute-deploy-branch-and-context.outputs.DEPLOY_BRANCH }}"
      - name: Generate dummy changes
        run: |
          date > generated.txt
          git config push.autoSetupRemote true
          git add .
          git commit -m "generated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ needs.compute-deploy-branch-and-context.outputs.DEPLOY_BRANCH }}
          force_with_lease: true
